version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///coins.db
      - PHOTO_BASE_URL=https://example.com/photos
    volumes:
      - ./coins.db:/app/coins.db
    restart: unless-stopped